# Leave server-uuid blank to generate a new one. Once it's been set, do not change it, or users will be able to verify a second time.
server-uuid: ""
orb-group-name: "orb-humans"
# If you want to require Orb verification, leave device-group-name blank.
device-group-name: "device-humans"
web-url: "https://minecraft.worldcoin.org"